# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get unix time
        id: deploy_time
        run: echo ::set-output name=DEPLOY_TIMESTAMP::$(date +%s)
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.x


      - name: Auto tagging
        id: tag_name
        uses: ButlerLogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
          tag_suffix: ".${{ steps.deploy_time.outputs.DEPLOY_TIMESTAMP }}"

      - name: Get file name
        id: source_file_name
        run: echo ::set-output name=SOURCE_FILE_NAME::blog-client-$GITHUB_BASE_REF-$NEW_TAG
        env:
          GITHUB_BASE_REF: ${{ env.GITHUB_BASE_REF }}
          NEW_TAG: ${{ steps.tag_name.outputs.tagname }}

      - name: ZIP source with git archive
        run: git archive --format=zip HEAD -o "$SOURCE_FILE_NAME.zip"
        env:
          SOURCE_FILE_NAME: ${{ steps.source_file_name.outputs.SOURCE_FILE_NAME }}

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          # AWS Access Key
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS Secret Key
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS Region
          region: ap-northeast-2
          # Beanstalk application name
          application_name: blog-study-nextjs
          # Beanstalk environment name. If empty a version will be created but not deployed anywhere.
          environment_name: Blogstudynextjs-env-1
          # Version label for new Beanstalk version
          version_label: ${{ env.SOURCE_FILE_NAME }}
          # Zip file with the version to deploy. If skipped the action will deploy existing version.
          deployment_package: ${{ env.SOURCE_FILE_NAME }}.zip
        env:
          SOURCE_FILE_NAME: ${{ steps.source_file_name.outputs.SOURCE_FILE_NAME }}
